### PR TITLE
Fix add shift command

### LINKED ISSUE #183: [PE-D] Add Shift is not working
Steps to reproduce:

1. key in `addShift -n Candice d/Monday-1 da/2021-10-01` (copied from user guide)
2. key in `change da/2021-10-01` (copied from user guide)
3. key in `viewShift -d monday-1`

Expected Result: to view shift?

Actual Result: Invalid command format! Also there's a missing space between if and only " Ifonly one date is provided, the end date is assumed to be seven days later."

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: RachelCheah/ped#13

### LINKED ISSUE #185: [PE-D] Nothing is showing up in the schedule after I add a shift
Steps to reproduce:

1. key in `addShift -n David d/Tuesday-1`
2. key in `addShift -n David d/Tuesday-1 da/2021-10-01`
key in `change da/2021-10-01`

Expected Result: to view shift?

Actual Result: Nothing is appearing on the schedule UI

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: RachelCheah/ped#15

### PR DESCRIPTION
**Pull request by IrvingHe000**
Update class related to `addShift` and add more test cases.

closes #185
closes #183

### CODE REVIEW

**Review by Gabau — APPROVED** [review]
LGTM, note that the way addShift interperates the default date is going to change with #237 towards the next date however. Will have to change the call to ParserUtil in the future.

**Comment by IrvingHe000** [comment]
So if you don't specify `da/`, is it choosing the day in the current week, or choose from the next 7 days starting with the current day?

**Comment by Gabau** [comment]
Should be next 7 days, its specified in #237 anyway, just have to change the test case when the time comes.

**Review by mweeruien — APPROVED** [review]
LGTM!

**Pull request merged**
